site_name: Projeto Erro 200

theme:
  name: material
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch between light and dark mode
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share

nav:
  - Home: index.md
  - Base:
    - Visão Geral: base/documento_de_visao.md
    - Metodologia: base/metodologia.md
    - 5W2H: base/5w2h.md
    - Brainstorm: base/Brainstorm.md
    - Mapa Mental: base/mapa_mental.md
    - Entrevista: base/entrevista.md
    - Pesquisa: base/pesquisa.md
    - Protótipo Alta Fidelidade: base/prototipo_alta_fidelidade.md
  - Modelagem:
    - Overview: modelagem/index.md
    - Diagrama de Classes: modelagem/diagrama_de_classes.md
    - Arquitetura do Sistema: modelagem/das.md
  - API:
    - Visão Geral: api/overview.md
    - Autenticação: api/authentication.md
    - Endpoints: api/endpoints.md
    - Fluxo de Status: api/status-flow.md
  - Interação:
    - Sprint 1: interacao/interacao1.md