# Generated by Django 5.2.1 on 2025-05-21 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Porto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("doca", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Posto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("armario", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_proposto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "valor_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A_CONFIRMAR", "Aguardando Confirmação"),
                            ("ACEITO", "Aceito pelo Entregador"),
                            ("EM_TRANSITO", "Em Trânsito para Porto"),
                            ("NO_PORTO", "Entregue ao Porto"),
                            ("EM_TRAVESSIA", "Em Travessia"),
                            ("NO_POSTO", "No Posto de Destino"),
                            ("ENTREGUE", "Entregue ao Cliente"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        default="A_CONFIRMAR",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barqueiro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_barqueiro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entregador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_entregador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("itens", models.ManyToManyField(to="myapp.item")),
                (
                    "porto_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_origem",
                        to="myapp.porto",
                    ),
                ),
                (
                    "posto_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_destino",
                        to="myapp.posto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("MORADOR", "Morador"),
                            ("ENTREGADOR", "Entregador"),
                            ("BARQUEIRO", "Barqueiro"),
                            ("ADMIN", "Administrador"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
