# Generated by Django 5.2.1 on 2025-05-14 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_produto_disponivel_pedido_itempedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidoCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='myapp.pedido')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
